title: Budget Data Package
author: Open Knowledge Labs
authorurl: http://okfnlabs.org/
github: http://github.com/openspending/budget-data-package
mailinglist: http://discuss.okfn.org/c/openspending
twitter: OpenSpending
googleanalytics: UA-33874954-31
