title: Fiscal Data Package
author: Open Knowledge Labs
authorurl: http://okfnlabs.org/
github: http://github.com/openspending/budget-data-package
mailinglist: http://lists.okfn.org/mailman/listinfo/openspending
twitter: OpenSpending
googleanalytics: UA-33874954-31
